Feature/core 803 add evan to universal resolver
evannetwork/evan-did-driver pull request #1
Opened 2020-01-20 07:56 UTC by OmairLiaquatAli

2020-01-20 15:53 UTC, wulfraem requested changes
Do we need the `yarn.lock` file?

2020-01-20 15:53 UTC, wulfraem commented on package.json
> +    "test": "echo 'No tests yet'"
which one of the test sections is intended to be used?

2020-01-20 15:57 UTC, wulfraem requested changes

2020-01-20 15:57 UTC, wulfraem commented on package.json
> +  "version": "1.0.0",
```suggestion
  "version": "0.1.0",
```
Universal resolver refers to this driver as version 0.1 [here](http://github.com/evannetwork/universal-resolver/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8R67). Or should universal resolvers reference be updated?

2020-01-21 09:28 UTC, S3bb1 approved these changes

2020-01-21 12:21 UTC, wulfraem approved these changes

2020-01-21 13:33 UTC, merged