add core did support
evannetwork/evan-did-driver pull request #3
Opened 2020-03-13 08:17 UTC by S3bb1

- [CORE-870]

2020-03-16 06:53 UTC, wulfraem requested changes

2020-03-16 06:53 UTC, wulfraem commented on src/index.ts
> +  if(req.params.did.indexOf('testcore')) {
```suggestion
  if (req.params.did.startsWith('did:evan:testcore:')) {
```

2020-03-16 06:53 UTC, wulfraem commented on src/index.ts
>      res.sendStatus(404)
```suggestion
    res.sendStatus(404);
```

2020-03-16 10:19 UTC, Tschuck approved these changes

2020-03-16 10:19 UTC, Tschuck commented on src/index.ts
```suggestion
```

2020-03-17 06:33 UTC, wulfraem approved these changes

2020-03-17 06:33 UTC, merged